From xxx.xxx.com:node-13.12

RUN mkdir -p /opt/build /opt/run

RUN cd /opt/build

git clone https://github.com/async-labs/builderbook.git

RUN cd /opt/run

git clone https://github.com/pasanmd/builderbook-build-repo

RUN build.sh
